In [1]:
import numpy as np

In [2]:
gamma = 0.95
epsilon = 0.01

In [22]:
r = np.array([[-0.4,0],[2,0],[-1,-0.5]])
P = np.array([
            [[0.45,0,0.55],[0,0,1],[0.6,0,0.4]]
            ,
            [[0,0,1],[0.5,0.4,0.1],[0,0.9,0.1]]
            ])
actions = [0,1]
states = [0,1,2]

In [4]:
#FOR THE STATE 0 TEST
v_0 = np.array([0, 0, 0])
v = np.array([2, 2.3, 2.9])
v_opt = -float("inf")
for a in actions:
    temp = r[0,a] + gamma*(v.dot(P[a][0,:]))
    if temp > v_opt:
        v_opt = temp
v_opt

2.7549999999999999

In [5]:
np.max(r[0,:]+gamma*P[:,0,:].dot(v))

2.7549999999999999

In [6]:
v = np.array([0, 0, 0])
v_temp = np.array([0, 0, 0])
for s in states:
    v_temp[s] = np.max(r[s,:]+gamma*P[:,s,:].dot(v))
v_temp = v

In [12]:
v = np.array([0, 0, 0])
for i in range(10):
    v_temp = np.array([0, 0, 0])
    for s in states:
        print(i, v)
        v_temp[s] = np.max(r[s,:]+gamma*P[:,s,:].dot(v))
        print(i, s ,v_temp)
    v = v_temp.copy()

0 [0 0 0]
0 0 [0 0 0]
0 [0 0 0]
0 1 [0 2 0]
0 [0 0 0]
0 2 [0 2 0]
1 [0 2 0]
1 0 [0 0 0]
1 [0 2 0]
1 1 [0 2 0]
1 [0 2 0]
1 2 [0 2 1]
2 [0 2 1]
2 0 [0 0 0]
2 [0 2 1]
2 1 [0 2 0]
2 [0 2 1]
2 2 [0 2 1]
3 [0 2 1]
3 0 [0 0 0]
3 [0 2 1]
3 1 [0 2 0]
3 [0 2 1]
3 2 [0 2 1]
4 [0 2 1]
4 0 [0 0 0]
4 [0 2 1]
4 1 [0 2 0]
4 [0 2 1]
4 2 [0 2 1]
5 [0 2 1]
5 0 [0 0 0]
5 [0 2 1]
5 1 [0 2 0]
5 [0 2 1]
5 2 [0 2 1]
6 [0 2 1]
6 0 [0 0 0]
6 [0 2 1]
6 1 [0 2 0]
6 [0 2 1]
6 2 [0 2 1]
7 [0 2 1]
7 0 [0 0 0]
7 [0 2 1]
7 1 [0 2 0]
7 [0 2 1]
7 2 [0 2 1]
8 [0 2 1]
8 0 [0 0 0]
8 [0 2 1]
8 1 [0 2 0]
8 [0 2 1]
8 2 [0 2 1]
9 [0 2 1]
9 0 [0 0 0]
9 [0 2 1]
9 1 [0 2 0]
9 [0 2 1]
9 2 [0 2 1]


In [8]:
v

array([0, 2, 1])

In [ ]:
v = np.array([0, 0, 0])
v_temp = np.array([0, 0, 0])
opt_policy = np.array([0, 0, 0])

for i in range(10):
    for s in states: 
        v_opt = -float("inf")
        for a in actions:
            temp = r[s,a] + gamma*(v.dot(P[a][s,:])) 
            if temp > v_opt:
                v_opt = temp
                v_temp[s] = temp
                opt_policy[s] = a
        v = v_temp.copy()
opt_policy

In [ ]:
gamma = 0.95
u = v.copy()
delta = 0

while delta<epsilon*(1-gamma)/gamma:
    for s in states:
        v_temp[s] = np.max(r[s,:]+gamma*P[:,s,:].dot(v))
    v = v_temp
    if np.linalg.norm(v-u) > delta:
        delta = np.linalg.norm(v-u)
    print(v)

In [ ]:
gamma = 0.5
u = v.copy()
delta = 0

while delta<epsilon*(1-gamma)/gamma:
    v = np.max(r + gamma*P.dot(v),axis=0)
    if np.linalg.norm(v-u) > delta:
        delta = np.linalg.norm(v-u)
    print(v)

In [18]:
temp = np.zeros((len(states)))

In [19]:
temp

array([ 0.,  0.,  0.])

In [20]:
P_Pi = np.zeros((3,3))

In [21]:
P_Pi

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
pi = [1,0,1]
for i in range(3):
    for j in range(3):
        P_Pi[i,j] = P[pi[i],i,j]
        

In [24]:
P_Pi

array([[ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0.9,  0.1]])

In [25]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.identity(3) - gamma*P_Pi

array([[ 1.   ,  0.   , -0.95 ],
       [ 0.   ,  1.   , -0.95 ],
       [ 0.   , -0.855,  0.905]])

In [31]:
r_pi = np.zeros((3))
for i in range(3):
    r_pi[i] = r[i,pi[i]]
r_pi

array([ 0. ,  2. , -0.5])

In [29]:
np.linalg.inv(np.identity(3) - gamma*P_Pi).dot(r_pi)

array([ 12.393531 ,  14.393531 ,  13.0458221])

In [1]:
A = [ 1.  0.  1.]

SyntaxError: invalid syntax (<ipython-input-1-4f8fa7f850e2>, line 1)

In [ ]:
# Q4 
E = 7000
Tmax = 100
Q = [[[0 for a in range(len(env.state_actions[x]))] for x in range(len(env.state_actions))] for i in range(1+E)]
N = [[[0 for a in range(len(env.state_actions[x]))] for x in range(len(env.state_actions))] for i in range(1+E)]
gamma = 0.95
env.render = False
for i in range(E):
    x0 = env.reset()
    a0_int = np.random.randint(len(env.state_actions[x0]))
    a0 = env.state_actions[x0][a0_int]
    x = [x0]
    a = [a0]
    N[i][x0][a0_int] += 1
    t = 0
    while True:
        xt, rt, term = env.step(x[t], a[t])
        x.append(xt)
        a.append(0 if (0 in env.state_actions[x[t+1]]) else 3)
        Q[i][x0][a0_int] += (gamma**t)*rt
        t+=1
        if t > Tmax or term:
            break
    N[i+1] = copy.deepcopy(N[i])
    Q[i+1] = copy.deepcopy(Q[i])

V = [[0 for x in range(len(env.state_actions))] for i in range(E+1)]
for i in range(len(Q)):
    for j in range(len(Q[i])):
        for k in range(len(Q[i][j])):
            if N[i][j][k] != 0:
                Q[i][j][k]/=N[i][j][k]
        if 0 in env.state_actions[j]:
            apol_int = 0
        else:
            for l in range(len(env.state_actions[j])):
                if env.state_actions[j][l] == 3:
                    apol_int = l
                    break
        V[i][j] = Q[i][j][apol_int]
        